{
 "title": "Burnout-Processor-Provision",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "orgId", "query": { "query": "label_values(orgId)" } }
  ]
 },
 "panels": [
  {
   "title": "System Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "saa_burnout_processor_system_memory_usage",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "saa_burnout_processor_system_cpu_usage",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Event Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Events received",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(saa_burnout_processsor_event_status_total{orgId=\"$orgId\"})"
    }
   ]
  },
  {
   "title": "Events Consumed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "saa_burnout_processsor_event_status_total{status=\"Consumed\", orgId=\"$orgId\"}"
    }
   ]
  },
  {
   "title": "Processed Succesfully",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "saa_burnout_processsor_event_status_total{status=\"Produced\", orgId=\"$orgId\"}"
    }
   ]
  },
  {
   "title": "Runtime exceptions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "saa_burnout_processsor_event_status_total{status=\"runtime_exception\", orgId=\"$orgId\"}"
    }
   ]
  },
  {
   "title": "Processing Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processing Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "saa_burnout_processor_total_processing_time_seconds{orgId=\"$orgId\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}