apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agentburnout-detector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    grafana_dashboard: "yes"
{{ include "agentburnout-detector.labels.standard" . | indent 4 }}
data:
  agentburnout-detector.json: |-
{{ .Files.Get "grafana/agentburnout-detector.json" | indent 4}}
