apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "agentburnout-detector.fullname" $ }}-sm
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
    - port: http
      path: /metrics
  selector:
    matchLabels:
      appService: "{{ .Values.env.required.appName }}{{ .Values.env.optional.appPrefix }}"