image:
  tag: REPLACE_WITH_TAG
  # tag: latest

env:
  required:
    DC: qaus1
    DAL_SEARCH_API: https://dal-search.qaus1.ciscoccservice.com/data-api/search
    CONFIG_SERVICE_URL: https://config-service.qaus1.ciscoccservice.com
    REDIS_HOST: clustercfg.qaus1-sunlight.ik2bpp.use1.cache.amazonaws.com
    BROKER_URL: https://idbrokerbts.webex.com/idb
    CLIENT_ID: C6781d7076c30fe68ee624a89acd439af72b02f9a4a0b0fff63592d068333b20c
    CLIENT_SECRET: ff2eebe0778202d88dec945c13340f5eddfd31a77225fdb133eeb2351980cbf9
  optional:
    appPrefix: JENKINS_ENV.APPNAME_PREFIX
