apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "burnout-processor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    grafana_dashboard: "yes"
{{ include "burnout-processor.labels.standard" . | indent 4 }}
data:
  burnout-processor.json: |-
{{ .Files.Get "grafana/burnout-processor.json" | indent 4}}
