apiVersion: v1
kind: Service
metadata:
  name: {{ include "abac-transcription-processor.deploymentName" . }}
  labels:
    appService: {{ include "abac-transcription-processor.deploymentName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    appService: {{ include "abac-transcription-processor.deploymentName" . }}