{
 "title": "Agent-burnout-detector-final-1",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "orgId", "query": { "query": "label_values(orgId)" } }
  ]
 },
 "panels": [
  {
   "title": "System Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "saa_ab_detector_system_memory_usage",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "saa_ab_detector_system_cpu_usage",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "EVENT STATUS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(saa_ab_detector_event_status_total{orgId=\"$orgId\"})",
     "legendFormat": "Total events"
    }
   ]
  },
  {
   "title": "EVENTS CONSUMED",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "saa_ab_detector_event_status_total{status=\"Consumed\",orgId=\"$orgId\"}"
    }
   ]
  },
  {
   "title": "EVENTS PROCESSED SUCCESSFULLY ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "saa_ab_detector_event_status_total{status=\"Produced\",orgId=\"$orgId\"}"
    }
   ]
  },
  {
   "title": "Runtime exceptions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "saa_ab_detector_event_status_total{status=\"runtime_exception\",orgId=\"$orgId\"}"
    }
   ]
  },
  {
   "title": "Processing times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Model Training Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "saa_ab_detector_model_training_time{orgId=\"$orgId\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Processing time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "saa_ab_detector_total_processing_time_seconds{orgId=\"$orgId\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}