FROM 244386282524.dkr.ecr.us-west-2.amazonaws.com/ccbu/base/amazon_jre17_base:17.0.10-24.02.16

ADD target/cache-validator-agentburnout-1.0.jar cache-validator-agentburnout-1.0.jar
CMD exec java -jar cache-validator-agentburnout-1.0.jar
