apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentburnout-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
  labels:
    appService: "{{ .Values.env.required.appName }}{{ .Values.env.optional.appPrefix }}"
{{ include "agentburnout-api.labels.standard" . | indent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    appService: "{{ .Values.env.required.appName }}{{ .Values.env.optional.appPrefix }}"
